# SPDX-FileCopyrightText: 2026 Arthur Mouraud
# SPDX-License-Identifier: Apache-2.0
# @package _global_
policy:
  name: diffusion
  pretrained_repo: null
  n_obs_steps: 2
  n_action_steps: 8
  num_inference_steps: 10
  input_shapes:
    observation.state: [3]
  output_shapes:
    action: [8]
